name: influencer-management

services:
  postgres:
    image: postgres:16.8-alpine3.20
    ports:
      - '5432:5432'
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:2025.4.22-debian-12-r0
    ports:
      - '9090:9000'
      - '9091:9001'
    env_file:
      - .env.docker
    volumes:
      - minio_data:/bitnami/minio/data

volumes:
  postgres_data:
  minio_data:
