name: influencer-management

services:
  postgres:
    image: postgres:16.8-alpine3.20
    ports:
      - '5432:5432'
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
